ECS_CLUSTER=${cluster_name}
ECS_DATADIR=/data/
ECS_CHECKPOINT=true
AWS_DEFAULT_REGION=eu-central-1
ECS_LOGLEVEL=debug
ECS_DOCKER_GRAPHPATH=/run/docker
ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=30m
ECS_RESERVED_MEMORY=512